import "@/styles/globals.css";
import Head from "next/head";
import { Toaster } from "react-hot-toast";



import Header from "../components/Header";
import Footer from "../components/Footer";



export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Fitness</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;0,900;1,200&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <Toaster position="top-center" reverseOrder={false} />
      <Header />
     <Component {...pageProps} />
      <Footer />
    </>
  );
}
